spring:
  application:
    name: com-barchy-payment
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/purchase_income
server:
  port: 8001
